network = input('Enter network name: ', 's');
PertFile = strcat(network, "_Pert.csv");
pertdata = readtable(PertFile);
index = find(pertdata.name == "WT");
pertdata.Properties.VariableNames = ["Names", "Positive", "Negative", ...
    "FrusB", "Plasticity", "JSDR", "NoSigFrusB", "FrusR", "NoSigFrusR"];
PosFeed = pertdata.Positive;
Plast = pertdata.Plasticity;
NegFeed = pertdata.Negative;
JSD = pertdata.JSDR;

X1 = PosFeed-PosFeed(index);
Xlab = '\Delta Positive Feedback Loops';
max(X1) - (min(X1)-max(X1))*0.05
min(X1) + (min(X1)-max(X1))*0.05
Xmin = input('Xmin = ');
XtickS = input('XtickS = ');

% Plasticity plot
Y1 = Plast/Plast(index);
Ylab = "Fold change in PS1 from WT";
max(Y1) - (min(Y1)-max(Y1))*0.05
min(Y1) + (min(Y1)-max(Y1))*0.05
Ymin = input('Ymin = ');
YtickS = input('YtickS = ');
fileName = strcat(network, "_Pos_plot");

% c1 = Plast/Plast(index);
createfigure(X1, Y1, c1,Xlab, Ylab, Xmin, XtickS, Ymin, YtickS, fileName);

function createfigure(X1, Y1,c1, Xlab, Ylab, Xmin, XtickS, Ymin, YtickS, fileName)
%CREATEFIGURE(X1, Y1)
%  X1:  scatter x
%  Y1:  scatter y

%  Auto-generated by MATLAB on 06-Feb-2020 17:45:46
Xmax = max(X1) - (min(X1)-max(X1))*0.05;
Ymax = max(Y1) - (min(Y1)-max(Y1))*0.05;
Xminl = min(X1) + (min(X1)-max(X1))*0.05;
Yminl = min(Y1) + (min(Y1)-max(Y1))*0.05;
[rho,p] = corr(X1, Y1);
if p < 0.0001
    str = '****';
elseif p < 0.001
    str = '***';
elseif p < 0.01
    str = '**';
elseif p < 0.05
    str = '*';
else
    str = '';
end
rhos = string(rho);
% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
% scatter(X1,Y1,'MarkerFaceColor',[0 0.447058826684952 0.74117648601532]);
scatter(X1,Y1,36,'filled');
% colorbar;
xlim(axes1, [Xminl Xmax]);
ylim(axes1, [Yminl Ymax]);
% Create ylabel
ylabel(Ylab);

% Create xlabel
xlabel(Xlab);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-1800 50]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.65 0.98]);
box(axes1,'on');
% Set the remaining axes properties
Xtick = Xmin:XtickS:Xmax;
Ytick = Ymin:YtickS:Ymax;
set(axes1,'FontName','Arial','FontSize',20,'FontWeight','bold',...
    'YTick',Ytick, 'XTick', Xtick, 'XTickLabelRotation',45);
% annotation(figure1,'textbox',...
%     [0.409088623115868 0.88139210844217 0.269982709320202 0.048742710120068],...
% 0.627014953265936 0.215931978638381 0.269982709320203 0.048742710120068
% 0.189088623115868 0.8760039210844217 0.269982709320202 0.048742710120068
%     'String',...
%     str,...
%     'LineStyle','none',...
%     'FontSize',16,...
%     'FontName','Arial',...
%     'FitBoxToText','off');
annotation(figure1,'textbox',...
    [0.577014953265936 0.265931978638381 0.269982709320203 0.048742710120068],...
    'String',sprintf("\\rho = %s%s", rhos, str),...
    'LineStyle','none',...
    'FontSize',16,...
    'FontName','Arial',...
    'FitBoxToText','off');

set(gcf, "position", [1 1 650 500]);
print(fileName, '-dtiff','-r600');
savefig(fileName);

end
