
%CREATEFIGURE(X1, Y1)
%  X1:  scatter x
%  Y1:  scatter y

%  Auto-generated by MATLAB on 04-Sep-2019 09:39:05

% Create figure
figure('PaperUnits','inches');

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'MarkerEdgeColor',[0 0.447058826684952 0.74117648601532],...
    'LineWidth',4);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.02 0.62]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1.9]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Arial','FontSize',20,'FontWeight','bold');
