
%CREATEFIGURE(X1, Y1)
%  X1:  scatter x
%  Y1:  scatter y

%  Auto-generated by MATLAB on 25-Aug-2019 17:51:53

% Create figure
figure;

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create scatter
scatter(OVOL.VarName7, OVOL.VarName71,'MarkerFaceColor',[0 0.447058826684952 0.74117648601532],...
    'MarkerEdgeColor',[0 0.447058826684952 0.74117648601532],...
    'LineWidth',4);

% Create ylabel
ylabel('RACIPE JSD from WT');

% Create xlabel
xlabel('Boolean JSD from WT');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.008 0.16]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.005 0.162]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Arial','FontSize',20,'FontWeight','bold');
